export {default as Header} from './Header/Header'
export {default as Hero} from './Hero/Hero'
export {default as Home} from './Home/Home'
export {default as Title} from './Titles/Title1/Title'
export {default as Footer} from './Footer/Footer'